{
    'name': 'Website Preorder',
    'sequence': '1',
    'summary': """order for purchase in advance""",
    'description': """order for purchase in advance""",
    'category': 'Sales',
    'author': 'Weblytic Labs',
    'company': 'Weblytic Labs',
    'website': "https://store.weblyticlabs.com",
    'depends': ['base', 'sale', 'purchase', 'product', 'website', 'stock', 'website_sale', 'mail', 'auth_signup',
                'portal',
                'crm'],
    'data': [
        'security/ir.model.access.csv',
        'data/installment_product.xml',
        'data/email_template_notify_details.xml',
        'views/res_config_settings_views.xml',
        'views/product.xml',
        'views/templates.xml',
        'views/product_timer.xml',
        'views/product_payment_method_view.xml',
        'views/preorder_label_view.xml',
        'views/preorder_list_view.xml',
        'views/preorder_submenu_view.xml',
        'views/my_account_preorder_view.xml',
        'views/my_portal_preorder_view.xml',
        'views/notify_view.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'wbl_website_preorder/static/src/js/wbl_timer.js',
            'wbl_website_preorder/static/src/js/partial_payment.js',
            'wbl_website_preorder/static/src/js/dynamic_payment.js',
            'wbl_website_preorder/static/src/js/notify.js',
            'wbl_website_preorder/static/src/css/preorder_label.css',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
}
